export const CURRENCY_SEACRH_REQUEST = 'CURRENCY_SEACRH_REQUEST';
export const CURRENCY_SEACRH_RESPONSE = 'CURRENCY_SEACRH_RESPONSE';
export const CURRENCY_SEACRH_FAILED = 'CURRENCY_SEACRH_FAILED';

export const CURRENCY_ADD_REQUEST = 'CURRENCY_ADD_REQUEST';
export const CURRENCY_ADD_RESPONSE = 'CURRENCY_ADD_RESPONSE';
export const CURRENCY_ADD_FAILED = 'CURRENCY_ADD_FAILED';

export const CURRENCY_REMOVE_REQUEST = 'CURRENCY_REMOVE_REQUEST';
export const CURRENCY_REMOVE_RESPONSE = 'CURRENCY_REMOVE_RESPONSE';
export const CURRENCY_REMOVE_FAILED = 'CURRENCY_REMOVE_FAILED';
